spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://81.71.48.29:3308/demo001?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: demo001
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # ???????????
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # ?????????????
    maxWait: 60000
    # ???????????????????????????????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????????
    minEvictableIdleTimeMillis: 300000
    # Oracle???select 1 from dual
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # ??PSCache??????????PSCache???
    poolPreparedStatements: true
    # ?????????filters????????sql?????'wall'?????
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    # ????DruidDataSource?????
    useGlobalDataSourceStat: true
    # ??connectProperties?????mergeSql????SQL??
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
